version: "3"

services:

  web-cont:
    build: ./web_app
    command: run_app.sh
    ports:
      - 5001:5000
    environment:
      FLASK_APP: app.py
      APP_FOLDER: /usr/src/app
      FLASK_ENV: development
      SECRET_KEY: gBI5ose5Z9CAW3HwcgKN
      FLASK_RUN_PORT: 5000
      DATABASE_URL: postgresql://barack_obama:qwe123QWE@db-cont:5432/the_base
      DATABASE: the_base
      SQL_HOST: db-cont
      SQL_PORT: 5432

  db-cont:
    build: ./db_app
    environment:
      POSTGRES_DB: the_base
      POSTGRES_USER: barack_obama
      POSTGRES_PASSWORD: qwe123QWE
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
